<?php

use Illuminate\Database\Seeder;

class CityTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \Illuminate\Support\Facades\DB::table("localities")->insert([
            ["state_id"=>25, "name"=>"Abule Egba"],
            ["state_id"=>25, "name"=>"Agbado"],
            ["state_id"=>25, "name"=>"Agbara"],
            ["state_id"=>25, "name"=>"Agege"],
            ["state_id"=>25, "name"=>"Ajah"],
            ["state_id"=>25, "name"=>"Ajao Estate"],
            ["state_id"=>25, "name"=>"Ajegunle"],
            ["state_id"=>25, "name"=>"Akoka"],
            ["state_id"=>25, "name"=>"Akowonjo"],
            ["state_id"=>25, "name"=>"Akute"],
            ["state_id"=>25, "name"=>"Alagbado"],
            ["state_id"=>25, "name"=>"Alakuko"],
            ["state_id"=>25, "name"=>"Alimosho"],
            ["state_id"=>25, "name"=>"Amuwo Odofin"],
            ["state_id"=>25, "name"=>"Anthony Village"],
            ["state_id"=>25, "name"=>"Apapa"],
            ["state_id"=>25, "name"=>"Ayobo"],
            ["state_id"=>25, "name"=>"Badagry"],
            ["state_id"=>25, "name"=>"Banana Island"],
            ["state_id"=>25, "name"=>"Bariga"],
            ["state_id"=>25, "name"=>"Berger"],
            ["state_id"=>25, "name"=>"Dopemu"],
            ["state_id"=>25, "name"=>"Ebute-Metta"],
            ["state_id"=>25, "name"=>"Egbeda"],
            ["state_id"=>25, "name"=>"Ejigbo"],
            ["state_id"=>25, "name"=>"Epe"],
            ["state_id"=>25, "name"=>"Fadeyi"],
            ["state_id"=>25, "name"=>"Festac Town"],
            ["state_id"=>25, "name"=>"Gbagada"],
            ["state_id"=>25, "name"=>"Iba"],
            ["state_id"=>25, "name"=>"Ibeju Lekki"],
            ["state_id"=>25, "name"=>"Idimu"],
            ["state_id"=>25, "name"=>"Ifako, Gbagada"],
            ["state_id"=>25, "name"=>"Ifako, Ijaiye"],
            ["state_id"=>25, "name"=>"Igando"],
            ["state_id"=>25, "name"=>"Iganmu"],
            ["state_id"=>25, "name"=>"Ijeshatedo"],
            ["state_id"=>25, "name"=>"Ijora 7up"],
            ["state_id"=>25, "name"=>"Iju Ishaga"],
            ["state_id"=>25, "name"=>"Ikeja"],
            ["state_id"=>25, "name"=>"Ikeja G. R. A."],
            ["state_id"=>25, "name"=>"Ikola/Command"],
            ["state_id"=>25, "name"=>"Ikorodu"],
            ["state_id"=>25, "name"=>"Ikorodu Road"],
            ["state_id"=>25, "name"=>"Ikotun"],
            ["state_id"=>25, "name"=>"Ikoyi"],
            ["state_id"=>25, "name"=>"Ilupeju"],
            ["state_id"=>25, "name"=>"International Airport Road"],
            ["state_id"=>25, "name"=>"Ipaja"],
            ["state_id"=>25, "name"=>"Isheri North"],
            ["state_id"=>25, "name"=>"Isolo"],
            ["state_id"=>25, "name"=>"Iyana Iba"],
            ["state_id"=>25, "name"=>"Iyana Ipaja"],
            ["state_id"=>25, "name"=>"Ketu"],
            ["state_id"=>25, "name"=>"Kiri Kiri"],
            ["state_id"=>25, "name"=>"LAGOS ABEOKUTA EXPRESSWAY"],
            ["state_id"=>25, "name"=>"Lagos Ibadan Expressway"],
            ["state_id"=>25, "name"=>"Lagos Island"],
            ["state_id"=>25, "name"=>"Lekki"],
            ["state_id"=>25, "name"=>"Lekki Phase 1"],
            ["state_id"=>25, "name"=>"Lekki Scheme 2"],
            ["state_id"=>25, "name"=>"Mafoluku"],
            ["state_id"=>25, "name"=>"Magodo"],
            ["state_id"=>25, "name"=>"Magodo Isheri"],
            ["state_id"=>25, "name"=>"MaryLand"],
            ["state_id"=>25, "name"=>"Mile 12"],
            ["state_id"=>25, "name"=>"Mile 2"],
            ["state_id"=>25, "name"=>"Mushin"],
            ["state_id"=>25, "name"=>"Obanikoro"],
            ["state_id"=>25, "name"=>"Ogba"],
            ["state_id"=>25, "name"=>"Ogudu GRA"],
            ["state_id"=>25, "name"=>"Ojo"],
            ["state_id"=>25, "name"=>"Ojodu Berger"],
            ["state_id"=>25, "name"=>"Ojokoro"],
            ["state_id"=>25, "name"=>"Ojota"],
            ["state_id"=>25, "name"=>"Ojuelegba"],
            ["state_id"=>25, "name"=>"Oka-Oba"],
            ["state_id"=>25, "name"=>"Okokomaiko"],
            ["state_id"=>25, "name"=>"Okota"],
            ["state_id"=>25, "name"=>"Olowo Ira"],
            ["state_id"=>25, "name"=>"Omole Estate Phase 1"],
            ["state_id"=>25, "name"=>"Omole Estate Phase 2"],
            ["state_id"=>25, "name"=>"Onipanu"],
            ["state_id"=>25, "name"=>"Oniru"],
            ["state_id"=>25, "name"=>"Opebi"],
            ["state_id"=>25, "name"=>"Oregun"],
            ["state_id"=>25, "name"=>"Oshodi"],
            ["state_id"=>25, "name"=>"Oshodi Apapa Expressway"],
            ["state_id"=>25, "name"=>"Oworonshoki"],
            ["state_id"=>25, "name"=>"Oyingbo"],
            ["state_id"=>25, "name"=>"Palmgroove"],
            ["state_id"=>25, "name"=>"Satellite Town"],
            ["state_id"=>25, "name"=>"Shogunle"],
            ["state_id"=>25, "name"=>"Shomolu"],
            ["state_id"=>25, "name"=>"Surulere"],
            ["state_id"=>25, "name"=>"Victoria Garden City (VGC)"],
            ["state_id"=>25, "name"=>"Victoria Island"],
            ["state_id"=>25, "name"=>"Yaba"]
        ]);
    }
}

